#!/bin/sh

function build_contracts () {
	pushd contract > /dev/null

	mkdir -p ../build

	(echo \" && awk 'FNR==1{print ""}1' metastarterstub.sol metastarter.sol etherstarter.sol | sed -e '/^import/d' | tr '\n' 'ß' | sed -e 's#ß#\\n#g' && echo \") | tr -d '\n' | sed 's#&#\\&#g' > ../build/solidity

	popd > /dev/null
}

function to_upper () {
	echo $1 | tr '[:lower:]' '[:upper:]'
}
