#!/bin/sh

. tools/mkcommon

function awk_line () {
	echo "BEGIN{getline l < \"build/$1\"}/$(to_upper $1)/{gsub(\"$(to_upper $1)\",l)}1"
}

build_contracts

cat test_template.js | awk "$(awk_line solidity)" > test.js;